name: Deploy to cPanel via SSH
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Jika Anda clone repo di server (folder repo terpisah dari docroot):
      - name: Pull & rsync on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/bustanu1/repositories/bisnisemasperak || exit 1
            git fetch --all
            git reset --hard origin/main
            rsync -av --delete --exclude ".git" --exclude ".github" --exclude ".cpanel.yml" --exclude "uploads/" ./ /home/bustanu1/bisnisemasperak.com

      # Jika Anda langsung clone ke document root, ganti script dengan:
      # cd /home/CPANELUSER/bisnisemasperak.com && git fetch --all && git reset --hard origin/main
